//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA47_Team12aCAProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberID { get; set; }
        public string MemberName { get; set; }
        public string ContactTitle { get; set; }
        public Nullable<int> Age { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Country { get; set; }
        public Nullable<int> BooksCurrentlyBorrowed { get; set; }
        public Nullable<decimal> FineAmt { get; set; }
        public string Notes { get; set; }
    }
}
